# Generated by cucumber-sinatra. (2015-01-09 12:36:04 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/ronin_badge_test.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RoninBadgeTest

class RoninBadgeTestWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RoninBadgeTestWorld.new
end
